### PR TITLE
Readme improvements

### PR DESCRIPTION
**Pull request by vazhnov**
I made some minor changes:
* split long text to paragraphs,
* changed 1-st level headers to 2-nd level
* added highlighting for a tearing notice
* added `.gitignore`

### CODE REVIEW

**Comment by vazhnov** [comment]
@slmisc , could you please take a look at this merge request?

**Comment by vazhnov** [comment]
@slmisc , ping :)

**Comment by vazhnov** [comment]
@slmisc , are you all right?

**Comment by slmisc** [comment]
I think the readme is fine as it is, thanks.

**Pull request closed without merging**
